name: 'Pull Request Title Validation'
description: 'The GitHub workflow action for validating of PR titles with regular expression'
inputs:
  regex:
    description: 'Regex to validate the pull request title'
    required: false
    default: '^[A-Z]+-\d+\s:\s.*?$'
  ignored_branch_prefixes:
    description: 'Comma separated list of prefixes in a branch name to ignore. eg: dependabot'
    required: false
    default: 'dependabot'
  github_token:
    description: 'The GitHub token'
    required: false
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: '../lib/pr-title-validation-action.js'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'